version: '3.8'

services:

  mongo:
    container_name: 'mongo'
    image: mongo
    ports:
      - '8001:27017'
    volumes:
      - db:/data/db
    networks:
      - kitapbar-net

volumes:
  db:

networks:
  kitapbar-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.15.57.0/24
